chore: update .gitignore
lonnieezell/codeigniter4-tasks pull request #122
Opened 2023-08-16 07:41 UTC by datamweb

2023-08-16 07:51 UTC, paulbalandan requested changes
Can you add a minimal gitignore file? Most of the changes here are IDE specific files. These should be added in a **global** gitignore file, not project-specific. If we are to add these, then all IDE files should be added here.

2023-08-16 07:55 UTC, datamweb commented
@paulbalandan This file is a copy of the shield.
I don't know exactly which items you mean. Can you suggest a change?

2023-08-16 08:00 UTC, paulbalandan commented on .gitignore
> +
Should be in global gitignore.

2023-08-16 08:00 UTC, paulbalandan commented on .gitignore
> +
Also these.

2023-08-16 08:00 UTC, paulbalandan commented on .gitignore
> +php_errors.log
How to generate?

2023-08-16 08:00 UTC, paulbalandan commented on .gitignore
> +
I don't think those are tests that should be ignored. Maybe this is in the wrong folder?

2023-08-16 08:00 UTC, paulbalandan commented on .gitignore
> +.vscode/
IDE specific files should NOT be per project ignore file.

2023-08-16 08:00 UTC, paulbalandan commented on .gitignore
> +/results/
what is this?

2023-08-16 08:13 UTC, kenjis commented
> Most of the changes here are IDE specific files. These should be added in a global gitignore file, not project-specific. If we are to add these, then all IDE files should be added here.

What if contributors do not ignore these files?

2023-08-16 08:21 UTC, datamweb commented
I was wondering how many people actually use global gitignore, I read about this today [here](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c).
Do the codeigniter community really have the necessary knowledge of these issues? I think most people's answer is no.

2023-08-16 08:32 UTC, paulbalandan commented
> What if contributors do not ignore these files?

Then I think it's time to educate them on these things.

2023-08-16 08:56 UTC, kenjis commented
I don't use global gitignore. Because I have never needed it.
It doesn't seem so easy to actually try to set it up.

But I agree with making gitignore simpler for projects.
Why don't you prepare the documentation for it first?

2023-08-17 12:32 UTC, MGatner commented
The Shield one is based off my Project template. I have a separate **.gitignore** for libraries that is specifically more minimalist: https://github.com/tattersoftware/codeigniter4-tools/blob/develop/src/Library/.gitignore

If these are desirable more generally we could incorporate them into DevKit. My Tools library basically spawned DevKit and then pared down to just a few things that didn't make it in.

2023-08-21 15:36 UTC, datamweb commented
Well, I'll close this one, there are currently **.gitignore** file is minimalist.
If there is a need to change, anyone can do it.

2023-08-21 15:36 UTC, closed without merging