Task runner
lonnieezell/codeigniter4-tasks pull request #17
Opened 2020-12-09 05:50 UTC by lonnieezell

- Implemented `shouldRun()` on Tasks. 
- Implemented the basic logic of TaskRunner::run().

NOTE: Since I've noticed other frameworks having notes regarding how using Timezones for scheduled tasks was problematic because runs could be missed or executed twice thanks to Daylight Savings time, I removed the ability to specify a timezone.

2020-12-09 13:22 UTC, MGatner reviewed
I will have to look at this on desktop bc there is too much happening for mobile.  It for the tests you need to set your GitHub secret for COMPOSER_AUTH

2020-12-09 15:15 UTC, MGatner requested changes
Looks pretty good, a few comments.

2020-12-09 15:15 UTC, MGatner commented on docs/index.md
> -| ->timezone('America/Chicago') | Specifies a timezone to use when determine if it runs.                |
Somehow this messed up the table formatting.
<img width="1041" alt="Screen Shot 2020-12-09 at 10 07 38 AM" src="https://user-images.githubusercontent.com/17572847/101647208-7447a800-3a06-11eb-9f71-181ab95353f3.png">

2020-12-09 15:15 UTC, MGatner commented on src/Task.php
> +		}
So Tasks can still specify timezones even if the Scheduler cannot check them?

2020-12-09 15:15 UTC, MGatner commented on src/TaskRunner.php
> +		}
I think the `try...catch` block should be just around `$task->run()` so we don't accidentally hide errors in `shouldRun()`.
```suggestion
		foreach ($tasks as $task)
		{
			if ($task->shouldRun())
			{
				try
				{
					$task->run();
				}
				catch (\Throwable $e)
				{
					log_message('error', $e->getMessage(), $e->getTrace());
				}
			}
		}
```

2021-01-23 00:13 UTC, MGatner commented
Too many changes for me to review on mobile - I'll check it out on desktop when I get a chance. Mention me when you're ready if I haven't gotten to it yet.

2021-03-02 03:56 UTC, lonnieezell commented
@MGatner changes pushed, please review again. 

There are a couple of PHPStan's not passing - and I don't believe they're accurate. Within TaskRunner, for example, unless `Time::now()` throws an exception, which I don't believe it can do, the variables should always be present within the final block.

2021-03-03 02:56 UTC, MGatner commented on src/TaskRunner.php
> +		}
@lonnieezell  I would still like to see this change.

2021-03-03 03:00 UTC, MGatner commented
I can pull this locally and take a look at the static analysis tomorrow. 

> Within TaskRunner, for example, unless Time::now() throws an exception, which I don't believe it can do, the variables should always be present within the final block.

`Time::now()` should be moved out of the `try` block then. `$output` will be conditional on the exception so I do think PHPStan is correct to flag that.

> spark

You have a whole copy of the **spark** file in this PR - accidental I assume??

2021-03-05 04:37 UTC, lonnieezell commented
@MGatner updated once again.

2021-03-05 14:50 UTC, MGatner commented
Looks good!

2021-03-05 14:50 UTC, MGatner approved these changes

2021-03-05 14:51 UTC, merged