Commands
lonnieezell/codeigniter4-tasks pull request #19
Opened 2021-02-26 21:34 UTC by colethorsen

Implemented commands:
tasks:run -runs the tasks using the task runner
tasks:list -lists the tasks. Note: the current cronexpression just returns the time for next up, once that is implemented it would show a better time
tasks:enable - enables tasks
tasks:disable - disabled tasks

settings are stored in a json file inside writable, and referenced in each of the different tasks. Currently there is only 1 setting.

2021-02-26 22:03 UTC, MGatner requested changes
Ive run out of time to go through the rest of this. Overall this looks like some great content! Please pay attention to the CodeIgniter 4 style guide, there are a number of differences (and I think some space indents instead of tabs). It might also be helpful to break this PR into smaller chunks if there are parts that are not interdependent.

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Disable.php
> +	];
This can come out.

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Disable.php
> +	 * Dsiables task running
```suggestion
	 * Disables task running
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Disable.php
> +		CLI::write(CLI::color('Tasks have been disabled.', 'red'));
Colors can be passed as a second parameter to `write`:
```suggestion
		CLI::write('Tasks have been disabled.', 'red');
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Enable.php
> +	];
```suggestion
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Enable.php
> +	 * Dsiables task running
```suggestion
	 * Enables task running
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Enable.php
> +		CLI::write(CLI::color('Tasks have been enabled.', 'green'));
```suggestion
		CLI::write('Tasks have been enabled.', 'green');
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Lister.php
> +class Lister extends BaseCommand
A little odd to have "Disable", "Enable", and "Lister". Maybe just "List"?

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Lister.php
> +	];
Remove

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Lister.php
> +			CLI::write(CLI::color('WARNING: Task running is currently disabled.', 'red'));
```suggestion
			CLI::write('WARNING: Task running is currently disabled.', 'red');
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Lister.php
> +			->init($scheduler);
```suggestion
		config('Tasks')->init($scheduler);
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Lister.php
> +		foreach($scheduler->getTasks() as $task) :
```suggestion
		foreach ($scheduler->getTasks() as $task)
		{
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Lister.php
> +		endforeach;
```suggestion
		}
```

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Lister.php
> +				   ]);
Looks like some extra indentations here?

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Settings.php
> +trait Settings
I'm not sure that making this a Trait adds anything. How about an abstract `TaskCommand` or similar? Then you could include common properties as well like `$group`.

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Settings.php
> +	protected function saveSettings($status)
I'm not opposed to the raw file code but we could also use a framework helper to handle the writes.

2021-02-26 22:03 UTC, MGatner commented on src/Commands/Settings.php
> +	 * save them.
```suggestion
	 * Gets the settings. If they
	 * have never been saved then create them.
```

2021-02-26 22:08 UTC, MGatner commented
I see now that you've built on #17. I think that's a good idea. Let's see if @lonnieezell can get that wrapped up so this PR can be rebased and be a bit smaller and cleaner.

2021-02-26 22:17 UTC, colethorsen commented on src/Commands/Disable.php
> +	];
If you want thats fine, I leave it in all my commands in case arguments might be helpful as development continues.

2021-02-26 22:19 UTC, colethorsen commented on src/Commands/Settings.php
> +	protected function saveSettings($status)
Its just based on the caching/logging code, we could if you find some benefit to doing it another way, thats fine.

2021-02-26 22:21 UTC, colethorsen commented on src/Commands/Settings.php
> +trait Settings
Yeah I like this, I'll update it accordingly.

2021-02-26 22:25 UTC, colethorsen commented on src/Commands/Lister.php
> +class Lister extends BaseCommand
List is a reserved keyword, so the class can't be called List. I've kept the naming of the command as tasks:list, if you have a non-reserved keyword suggestion I'm open

2021-02-26 22:38 UTC, colethorsen commented on src/Commands/Lister.php
> +				   ]);
Something weird about the automated code cleanup did this, I've fixed it up.

2021-02-26 22:43 UTC, colethorsen commented
This should all be largely resolved now.

2021-03-05 14:52 UTC, MGatner commented
@colethorsen Can you rebase now that #17 is merged? That should rerun tests, which are hopefully all fixed now.

2021-04-05 18:16 UTC, MGatner commented on src/Commands/Lister.php
> +				   ]);
Thanks! Yes the automated styler does that to me all the time 🙄

2021-04-05 18:17 UTC, MGatner commented on src/Commands/Disable.php
> +	];
I'm in favor of pulling it.

2021-04-05 18:21 UTC, MGatner requested changes
Looking good! Still a few content issues. Also looks like we still don't have the forked-repo Actions testing working yet. Have you run tests locally, successfully?

2021-04-05 18:21 UTC, MGatner commented on src/Commands/Lister.php
> +				   ]);
Looks like it still is over-indented, unless GitHub is showing me wrong?

2021-04-05 18:21 UTC, MGatner commented on src/Commands/Disable.php
> +	];
I'm in favor of pulling them.

2021-04-05 18:37 UTC, colethorsen commented on src/Commands/Lister.php
> +				   ]);
The automated code styler changed this again. Perhaps this is something that should be disabled, or fixed in whatever styler you're using that is causing this problem.

2021-04-22 11:57 UTC, MGatner commented
We still need to get the workflows working. I will pull this and test locally, but I think it is set! Thank you for the work.

2021-04-26 04:25 UTC, lonnieezell commented
This looks great. Thanks!

2021-04-26 04:25 UTC, merged