hours and minutes
lonnieezell/codeigniter4-tasks pull request #41
Opened 2022-01-19 16:20 UTC by colethorsen

hours and minutes previously supported an integer, but were cast as arrays which made it impossible to use an integer.

2022-01-21 12:47 UTC, MGatner commented
This repo needs to be bumped to PHP 7.4 before CI\CD succeeds. I will try to get to that today and then you can rebase.

2022-01-27 17:10 UTC, MGatner commented
@colethorsen Now that #43 is merged can you please rebase this?

2022-01-30 12:55 UTC, MGatner commented
Looks like Rector is picking up a preexisting issue. I'm not sure how that wasn't resolved in the DevKit PR but it was not caused by this.

2022-01-30 12:56 UTC, MGatner requested changes
Be sure to run CS Fixer to catch these style issues.

2022-01-30 12:56 UTC, MGatner commented on src/FrequenciesTrait.php
> +     * @param array|int $hours
```suggestion
     * @param array|int $hours
     *
```

2022-01-30 12:56 UTC, MGatner commented on src/FrequenciesTrait.php
> +     * @param array|int $minutes
```suggestion
     * @param array|int $minutes
     *
```

2022-04-06 21:20 UTC, lonnieezell commented
@MGatner is this good now?

2022-04-07 11:28 UTC, MGatner commented
It will probably still need to be run through Rector and CA Fixer but the content is good to me.

2022-04-07 13:13 UTC, merged