run a task at a specific time of day
lonnieezell/codeigniter4-tasks pull request #42
Opened 2022-01-19 16:20 UTC by colethorsen

-can be used in conjunction with the other frequency methods to easily set the time.

2022-01-21 12:49 UTC, MGatner commented
This needs the CI\CD updates too. But also please add tests for the new method, it should be a fairly easy copy-paste from a few existing tests.

2022-01-27 17:10 UTC, MGatner commented
@colethorsen Now that #43 is merged can you please rebase this?

2022-01-30 12:49 UTC, MGatner requested changes

2022-01-30 12:49 UTC, MGatner commented on src/FrequenciesTrait.php
> +     * @return $this
```suggestion
```

2022-04-06 21:19 UTC, lonnieezell commented
@MGatner is this good now?

2022-04-07 11:32 UTC, MGatner commented
Same - probably some cleanup but let's get the content in place.

2022-04-07 13:13 UTC, merged